// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexSHs9CGrp4bg5pKFiYlbY21FfVS95yA',
    appId: '1:761543835614:android:8c2a3104b6e03556ed674f',
    messagingSenderId: '761543835614',
    projectId: 'udomtimatable',
    storageBucket: 'udomtimatable.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf_2bmAaIfAMlTl40Rfz-WBwChIvwek1k',
    appId: '1:761543835614:ios:89473a1e736aa46ded674f',
    messagingSenderId: '761543835614',
    projectId: 'udomtimatable',
    storageBucket: 'udomtimatable.appspot.com',
    androidClientId: '761543835614-5a86jp2keo3r78ri34mm7iqamqvcd26c.apps.googleusercontent.com',
    iosClientId: '761543835614-m0itkmmiqk8esms13qau0bupqo7mvqjm.apps.googleusercontent.com',
    iosBundleId: 'com.anuarybryton.udomtimetable',
  );
}
